---
  - name: Install nginx and php
    apt:
      pkg:
      - nginx
      - unzip
      - php-imagick 
      - php7.4-fpm 
      - php7.4-mbstring 
      - php7.4-bcmath 
      - php7.4-xml 
      - php7.4-mysql
      - php7.4-common 
      - php7.4-gd 
      - php7.4-json 
      - php7.4-cli 
      - php7.4-curl 
      - php7.4-zip
      update_cache: yes

  - name: Config vhost nginx
    template: 
      src: vhost.nginx.conf.j2
      dest: /etc/nginx/sites-enabled/default

  - name: Baixar Wordpress
    ansible.builtin.unarchive:
      src: http://wordpress.org/latest.tar.gz
      dest: /var/www/html
      remote_src: yes

  - name: Alterando o arquivo wp-config
    template:
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php

  - name: Alterando permissão diretório wordpress
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: '0755'     

  - name: Restart Nginx
    service:
      name: nginx
      state: restarted 
